grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_1:
    class: XGBClassifier
    module: xgboost
    params:
      objective: binary:logistic
      eval_metric: logloss
      use_label_encoder: false
      random_state: 42
      scale_pos_weight: 3.51
    search_param_grid:
      n_estimators:
        - 100
        - 200
      max_depth:
        - 3
        - 5
        - 7
      learning_rate:
        - 0.01
        - 0.1
      subsample:
        - 0.8
        - 1.0
      colsample_bytree:
        - 0.8
        - 1.0